name: Release to PyPI

on:
  push:
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pipx install poetry
      
      - name: Install dependencies
        run: |
          poetry install --no-interaction
          poetry run pip install build twine
      
      - name: Run tests
        run: |
          poetry run pytest
          poetry run mypy src/
          poetry run ruff check .
      
      - name: Build package
        run: poetry run python -m build
      
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry run twine upload dist/*
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            
            This release includes:
            - Bug fixes and improvements
            - Enhanced documentation
            - Performance optimizations
            
            ## Installation
            
            ```bash
            pip install icat-data-quality==${{ github.ref_name }}
            ```
            
            ## Documentation
            
            See the [README](https://github.com/${{ github.repository }}) for usage examples and documentation.
          draft: false
          prerelease: false
